humanize_prompt="""Don't start until i give you the blog section in the second prompt.\
use the following steps to rewrite the blog section I will give you in the next prompt. \
Put the rewritten blog section in a code block. Make sure everything is fit into the code block. \
Don't repeat what you've already said in previous answers. Remove anything that is duplicate. \
Do you understand? Answer yes or no. \
Add in h3 tags where applicable and only every 200-250 words. \
IMPORTANT: Separate any paragraphs longer than 50 words into separate paragraphs with 'p' tags. \
Don't forget the closing h3 or p tags. \
IMPORTANT: Don't add anything introducing the drone such as "I recently stumbled upon" or "hey there" or "ever heard of". We already know what the product is. \
Lengthen the blog section to have six or more paragraphs but keep the same amount of h3 tags to the original and return the section in html format without the 'html' and 'body' tags. \
IMPORTANT: Don't forget to add ordered and unordered lists where applicable in html format. Add tables in html format where applicable. \
Conversational Tone: Use a conversational style of writing. Imagine you're speaking to a friend over a cup of coffee. This can often make the text feel more human-like and relatable. \
Use of Pronouns: Don't hesitate to use first-person pronouns like "I", "we", or second-person like "you" to establish a personal connection. Idiomatic Expressions: Include colloquialisms, idioms, or phrasal verbs that are commonly used in everyday speech. \
Variable Sentence Length: Use a mix of short, punchy sentences and longer, more complex ones to create a natural rhythm in your writing. Emotion and Opinion: Show emotion or include opinions to make the writing feel more personal and less like an automated response. \
Include Personal Anecdotes: Sharing personal stories or experiences can make your writing more engaging and relatable. \
Humor and Wit: Sporadically include humor or wit to keep the reader engaged and to lighten the tone when appropriate. \
Ask Questions: Pose rhetorical or direct questions to engage the reader and encourage them to think more deeply about the topic. \
Imperfect Grammar: While good grammar is important, the occasional colloquial expression or sentence fragment can make your text feel more natural. Active Voice: Using the active voice can make your writing seem more direct and engaging. \
Contractions: Use contractions like "I'm," "you're," "they're," etc., to make the text sound more conversational. \
Vary Vocabulary: Using a rich and varied vocabulary can make your text seem more human, but don't go overboard with jargon or overly complex words. \
Edit and Revise: Make sure to read the text aloud, or have someone else read it to ensure it sounds natural. Edit as needed. Use of Ellipses and Interjections: Occasionally use ellipses for pauses... or interjections like "Oh," "Well," "You see," to mimic natural speech patterns. \
Direct Address to the Reader: Occasionally speaking directly to the reader can enhance the sense of engagement and conversation. \
By incorporating these elements, your writing will likely come off as more human and might be less likely to be flagged as generated by AI. However, it's important to note that sophisticated AI detection tools may still be able to identify text as machine-generated based on various factors that are difficult to fully replicate or mask.

Use the following table of LSI keywords and try to match the keyword density. Only insert/change keywords where it makes sense to.
LSI Keyword table: {table}
"""

humanize_prompt_intro="""
Don't start until i give you the blog section in the second prompt. \
use the following steps to rewrite the blog section I will give you in the next prompt. \
Put the rewritten blog section in a code block. This is an introductory section for a blog article. \
Remove any 'h3' tags so you have only 'p' tags. Shorten the blog section until it is under 200 words total. \
Separate any paragraphs longer than 60 words into separate paragraphs. \
Keep a similar length and headings to the original and return the section in html format without the ‘html’ and ‘body’ tags. \
Don’t repeat what you’ve already said in previous answers. Do you understand? Answer yes or no. \
Conversational Tone: Use a conversational style of writing. Imagine you're speaking to a friend over a cup of coffee. \
This can often make the text feel more human-like and relatable. \
Use of Pronouns: Don't hesitate to use first-person pronouns like "I", "we", or second-person like "you" to establish a personal connection. \
Idiomatic Expressions: Include colloquialisms, idioms, or phrasal verbs that are commonly used in everyday speech. \
Variable Sentence Length: Use a mix of short, punchy sentences and longer, more complex ones to create a natural rhythm in your writing. \
Emotion and Opinion: Show emotion or include opinions to make the writing feel more personal and less like an automated response. \
Include Personal Anecdotes: Sharing personal stories or experiences can make your writing more engaging and relatable. \
Humor and Wit: Sporadically include humor or wit to keep the reader engaged and to lighten the tone when appropriate. \
Ask Questions: Pose rhetorical or direct questions to engage the reader and encourage them to think more deeply about the topic. \
Imperfect Grammar: While good grammar is important, the occasional colloquial expression or sentence fragment can make your text feel more natural. \
Active Voice: Using the active voice can make your writing seem more direct and engaging. \
Contractions: Use contractions like "I'm," "you're," "they're," etc., to make the text sound more conversational. \
Vary Vocabulary: Using a rich and varied vocabulary can make your text seem more human, but don't go overboard with jargon or overly complex words. \
Edit and Revise: Make sure to read the text aloud, or have someone else read it to ensure it sounds natural. Edit as needed. \
Use of Ellipses and Interjections: Occasionally use ellipses for pauses... or interjections like "Oh," "Well," "You see," to mimic natural speech patterns. \
Direct Address to the Reader: Occasionally speaking directly to the reader can enhance the sense of engagement and conversation. \
By incorporating these elements, your writing will likely come off as more human and might be less likely to be flagged as generated by AI. \
However, it's important to note that sophisticated AI detection tools may still be able to identify text as machine-generated based on various factors that are difficult to fully replicate or mask.

Use the following table of LSI keywords and try to match the keyword density. Only insert/change keywords where it makes sense to.
LSI Keyword table: {table}

"""